### ISSUE TITLE
Wrong python virtualenv in package

### ISSUE THREAD

**Issue by gjost** [densho/ddr-public#144]
It looks like the wrong Python version is installed  in the latest [ddrpublic-master_4.0.2~deb9_amd64.deb package](http://packages.densho.org/debian/pool/main/d/ddrpublic-master/ddrpublic-master_4.0.2~deb9_amd64.deb).

This package was uploaded at 03-Dec-2019 21:38 (UTC) and installed on the production server, where it appeared to work fine.

This morning at 11:00am the site was reported to be down.  I logged in to the server and saw that supervisord was flapping.  I logged in as `ddr`, ran `cd /opt/ddr-public; source venv/ddrpublic/bin/activate` then `python ddrpublic/manage.py runserver` and got this:
```
(ddrpublic) ddr@lightning:/opt/ddr-public$ python ddrpublic/manage.py runserver
Traceback (most recent call last):
  File "ddrpublic/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  ...
  File "/opt/ddr-public/ddrpublic/ddrpublic/settings.py", line 3, in <module>
    import configparser
ImportError: No module named configparser
```
This is what you get when you run Python and try to import the Python3 configparser (Python3 changed the name of the module).

I removed and reinstalled the `ddrpublic-master` package and got the same behavior.  I then deleted the virtualenv directory and recreated it using `make install-app`.  The app now runs with no apparent problems.

Here's the interesting thing: I downloaded the package onto a fresh VM, installed via gdebi, and got the same behavior.  However, the virtualenv appears to contain the correct Python3 version:
```
(ddrpublic) ddr@blank9:/opt/ddr-public$ ls venv/ddrpublic/lib/
python3.5
```

Question: How was the site running for the past couple days???

**Comment by gjost** [comment]
Just prepared a new package to fix an unrelated issue and had the same problem again.  Recently in my dev VM I've been keeping source code in a separate volume because I ran out of space in the (too small) main VM volume.  Maybe FPM gets confused with the symlinking?  I moved ddr-public to `/opt/`, recreated the venv, and then made a new package, and it looks like it works.

**Comment by gjost** [comment]
Fixed as of package `ddrpublic-master_4.0.3~deb9`.
